### ISSUE TITLE
Doesn't Vote Anymore

### ISSUE THREAD

**Issue by RuthlessRuler** [manciuszz/WebNovel-Login-Manager#1]
Sue to some design updates on Webnovel, the auto vote feature (With Power Stone & Energy Stones) doesn't work as it used to before.

Could you please update the script and add it to sites like Greasyfork?

**Comment by manciuszz** [comment]
I'll check it out. I'm planning to refactor the auto-vote feature, since webnovel.com added their own "countdown" timer in "Power & Energy Stones" page that I can take advantage of. This will remove the need to estimate the time based on last received stones and will work across all time-zones (cause I suspect that there was such an issue with it)

**Comment by manciuszz** [comment]
I checked for changes and well, everything still works, its just that the auto-vote feature seems pretty unreliable due to time estimation stuff... 

Anyways, **updated to v0.15** - now it will always vote until no power and energy stones are left simply because they are restocked every day and since they don't stack (they are valid for one day), there's no point in holding onto them, so I guess its always best to get rid of em. Now where those stones are spent - the script checks the book rankings and always spend them on top choices, which might not be something some people want, but can't be arsed and not really interested in implementing voodoo magic to determine what books you like or whatnot. 

Didn't really test the changes though (they should work), but there might appear some edge cases that I haven't thought of yet. I'll update according to the situation.

P.S I'll think about the publishing to Greasyfork, hopefully there is github integration there, otherwise I'll have to add an updater URL ...

**Comment by RuthlessRuler** [comment]
Thanks for the update. It now works on my End!
